name: A test workflow title
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
  
jobs:
  print-hello-world:
    runs-on: ubuntu-20.04
    environment: PROD
    steps:
      - name: Print hello world
        run: echo "Hello world!!"
        # quick edit

      - uses: azure/login@v1
        env:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 
