name: A test workflow title
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
  
jobs:
  print-hello-world:
    runs-on: ubuntu-20.04
    environment: PROD
    steps:
      - name: Print hello me
        run: echo "Hello $MY_NAME!!"
        # quick edit
        env:
          MY_NAME: ${{ vars.MY_NAME}}

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true
