name: PushToAny_NONPROD
on:
  pull_request:
    branches:
      - 'production'
      - 'non-production'
  workflow_dispatch:

# test
jobs:
  print-hello-world:
    runs-on: ubuntu-20.04
    environment: NONPROD
    steps:
      - uses: actions/checkout@v3

      - name: echo event name
        run: echo "${{ github.event_name }}"
      
      - name: Run Plan
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "Run Terraform PLAN on NONPROD" >> $GITHUB_STEP_SUMMARY
        env:
          MY_NAME: ${{ vars.MY_NAME}}

      - name: Run Apply
        run: echo "Run Terraform APPLY on NONPROD" >> $GITHUB_STEP_SUMMARY
        env:
          MY_NAME: ${{ vars.MY_NAME}}

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true
