name: PushToMain_PROD
on:
  pull_request:
    branches:
      - 'production'
      - 'non-production'
  workflow_dispatch:
  
jobs:
  print-hello-world:
    runs-on: ubuntu-20.04
    environment: PROD
    steps:
      - uses: actions/checkout@v3
      
      - name: Print hello me
        run: echo "Run Terraform PLAN on PROD" >> $GITHUB_STEP_SUMMARY
        env:
          MY_NAME: ${{ vars.MY_NAME}}

      - name: Print hello me
        run: echo "Run Terraform APPLY on PROD" >> $GITHUB_STEP_SUMMARY
        env:
          MY_NAME: ${{ vars.MY_NAME}}

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true
