name: PushToMain_PROD
on:
  pull_request:
    branches:
      - 'production'
  push:
    branches:
      - 'production'
  workflow_dispatch:
  
jobs:
  env_testing:
    runs-on: ubuntu-20.04
    environment: PROD
    steps:
      - uses: actions/checkout@v3

      - name: echo event name
        run: echo "${{ github.event_name }}"
      
      - name: Run Plan
        if: github.event_name == 'pull_request'
        run: echo "Run Terraform PLAN on PROD" >> $GITHUB_STEP_SUMMARY
        env:
          MY_NAME: ${{ vars.MY_NAME}}

      - name: Run Apply
        if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch' )
        run: echo "Run Terraform APPLY on PROD" >> $GITHUB_STEP_SUMMARY
        env:
          MY_NAME: ${{ vars.MY_NAME}}

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true
